import "@/css/globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// export const viewport = {
//   initialScale: 1,
//   width: "device-width",
//   maximumScale: 1,
//   userScalable: 0,
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
